language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - .dynamodb-local
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
before_install:
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
script: "sbt clean coverage test makeMicrosite"
after_success: "sbt coverageReport coveralls"